version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
    networks:
      - rust_hour_network

  # Adminer (Database GUI)
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - rust_hour_network
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db-data:
  cargo-cache:
  target-cache:

networks:
  rust_hour_network:
    driver: bridge